### ISSUE TITLE
Server side example?

### ISSUE THREAD

**Issue by nzfarmer1** [monteslu/udp-serial#2]
Hi

Do you have an example of the server side - i.e. an Arduino Sketch that converts a Serial connection back into a UDP connection?

thanks

**Comment by monteslu** [comment]
Here's an example of using an image on an ESP8266 that relays the packets back and forth to an arduino:  https://gist.github.com/ajfisher/5fe60fe7d8c49b3223f0

that help?

**Comment by nzfarmer1** [comment]
Thanks!
